const Product = [
  {
    id: "1",
    Name: "Aliquam lobortis",
    img: "../image/product-01-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "headphone",
    type: "sale",
    price: "255",
  },
  {
    id: "2",
    Name: "Auctor gravida enim",
    img: "../image/product-02-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "headphone",
    type: "new",
    price: "935",
  },
  {
    id: "3",
    Name: "Cillum dolore tortor nisl",
    img: "../image/product-03-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "watch",
    type: "sale",
    price: "845",
  },
  {
    id: "4",
    Name: "Condimentum posuere",
    img: "../image/product-04-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Accessories",
    type: "sale",
    price: "635",
  },
  {
    id: "5",
    Name: "Cras neque metus eugiat",
    img: "../image/product-05-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Accessories",
    type: "sale",
    price: "65",
  },
  {
    id: "6",
    Name: "Dignissim venenatis tellus",
    img: "../image/product-07-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Accessories",
    type: "sale",
    price: "59",
  },
  {
    id: "7",
    Name: "Aliquam lobortis",
    img: "../image/product-07-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Accessories",
    type: "",
    price: "235",
  },
  {
    id: "8",
    Name: "Dolorum fuga eget posuer",
    img: "../image/product-08-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Mobile",
    type: "new",
    price: "326",
  },
  {
    id: "9",
    Name: "Aliquam lobortis",
    img: "../image/product-09.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Mobile",
    type: "new",
    price: "85",
  },
  {
    id: "10",
    Name: "Laudantium enim fringilla dignissim",
    img: "../image/product-10-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "headphone",
    type: "new",
    price: "65",
  },
  {
    id: "11",
    Name: "Morbi ornare vestibulum massa at est",
    img: "../image/product-11-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Mobile",
    type: "new",
    price: "13",
  },
  {
    id: "12",
    Name: "Natus erro at congue massa",
    img: "../image/product-12-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "headphone",
    type: "",
    price: "75",
  },
  {
    id: "13",
    Name: "Nemo enim nec elementum dolor",
    img: "../image/product-13-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "headphone",
    type: "new",
    price: "29",
  },
  {
    id: "14",
    Name: "Nostrum exercitationem itae neque",
    img: "../image/product-14-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Mobile",
    type: "",
    price: "78",
  },
  {
    id: "15",
    Name: "Nullam maximus eget nisi dignissim",
    img: "../image/product-15-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Mobile",
    type: "",
    price: "49",
  },
  {
    id: "16",
    Name: "Mauris tincidunt eros posuere placera",
    img: "../image/product-16-270x270.jpg",
    des: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.Consetetur sadipscing elitr, sed diam nonumy eirmod.Suspendisse ultrices mauris diam",
    cat: "Accessories",
    type: "",
    price: "235",
  },
];
export default Product;
